export const WEBSITE_URL = 'https://hooosberg.com/apps/domprompter/'
export const SUPPORT_URL = 'https://hooosberg.com/apps/domprompter/'
export const PRIVACY_URL = 'https://hooosberg.com/privacy/'
export const TERMS_URL = 'https://hooosberg.com/terms/'
export const GITHUB_REPO_URL = 'https://github.com/hooosberg/DOMPrompter'
export const DEVELOPER_GITHUB_URL = 'https://github.com/hooosberg'
